LMS Salesforce project/force-app/main/default/objects/Course__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>Instructor__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active,</fullName>
                <default>true</default>
                <label>Active,</label>
            </value>
            <value>
                <fullName>Inactive,</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/EnrollmentDate__c.field-meta.xml
<CustomField>
    <fullName>EnrollmentDate__c</fullName>
    <label>EnrollmentDate</label>
    <type>Date</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>Instructor__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Instructor__c/Instructor__c.object-meta.xml
<CustomObject>
    <label>Instructor</label>
    <nameField>
        <label>Instructor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Instructor__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Instructors</relationshipLabel>
    <relationshipName>Instructors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Student__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LMS Salesforce project/force-app/main/default/classes/handlers/EnrollmentTriggerHandler.cls
public with sharing class EnrollmentTriggerHandler {
    public static void handleBeforeInsert(List<Enrollment__c> newEnrollment) {
        for(Enrollment__c er : newEnrollment){
            Id studentId = er.Student__c;
            Id courseId = er.Course__c;
            Date enrollmentDate = er.EnrollmentDate__c;
            Id statusId = er.Status__c;
            Id instructorId = er.Instructor__c;



            EnrollmentService.studentEnrollmentRules(
                studentId,
                courseId, 
                EnrollmentDate, 
                StatusId, 
                InstructorId
                );
        }
        
    }

    public static void handlerAfterInsert(List<Enrollment__c> newEnrrol){
        for(Enrollment__c enr : newEnrrol){
            Id studentId = enr.Student__c;
            Id courseId = enr.Course__c;
            Id instructorId = enr.Instructor__c; 
            Date enrollmentDate = enr.EnrollmentDate__c;
            Id statusId = enr.Status__c;

            EnrollmentService.enroll(
                studentId, 
                courseId, 
                InstructorId, 
                EnrollmentDate, 
                StatusId
                );
            
        }
    }

    public static void handlerAfterUpdate(List<Enrollment__c> newEnrrolUp, Map<Id, Enrollment__c> oldMap){
        


        for (Enrollment__c enr : newEnrrolUp) {
            Id enrollmentId = enr.Id;
            Id statusId = enr.Status__c;
            

            Enrollment__c old = oldMap.get(enr.Id);

            if (enr.Status__c != old.Status__c && enr.Status__r.Name == 'Canceled') {
                EnrollmentService.cancelEnroll(enrollmentId);
            }

            if (enr.Status__c != old.Status__c && enr.Status__r.Name == 'On Hold') {
                EnrollmentService.putOnHold(enrollmentId);
            }

            if (enr.Status__c != old.Status__c && enr.Status__r.Name == 'Approved') {
                EnrollmentService.approveEnroll(enrollmentId);
            }
        }

    }
}