LMS Salesforce project/force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/classes/repositorys/EnrollmentRepository.cls
public with sharing class EnrollmentRepository {
    public static List<Enrollment__c> getEnrollmentActives() {
        List<Status__c> enrollmentsStatus = [
            SELECT Id, Name 
            FROM Status__c
            WHERE Status__c IN ('Active', 'On Hold')
        ];


        Set<Id> statusIds = new Set<Id>();
        for(Status__c s : enrollmentsStatus){
            statusIds.add(s.Id);    
        }

        List<Enrollment__c> enrollments = [
            SELECT Id, Name, Status__c 
            FROM Enrollment__c 
            WHERE Status__c IN :statusIds
        ];
        

        return enrollments;
        
    }
}