LMS Salesforce project/force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <label>Certificate</label>
    <nameField>
        <label>Certificate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Certificate__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/classes/repositorys/CertificateRepository.cls
public with sharing class CertificateRepository {
    public static List<Certificate__c> getCertificateActive() {
        List<Student__c> completedStudents = StudentRepository.getCompletedStudents();
        Set<Id> studentIds = new Map<Id, Student__c>(completedStudents).keySet();
        List<Certificate__c> activeCertificates = [
            SELECT Id, Name
            FROM Certificate__c
            WHERE Student__c IN :studentIds
        ];

        return activeCertificates;

    }
}