LMS Salesforce project/force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <label>Certificate</label>
    <nameField>
        <label>Certificate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Certificate__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Certificate__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Certificate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Certificate__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active,</fullName>
                <default>true</default>
                <label>Active,</label>
            </value>
            <value>
                <fullName>Inactive,</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Enrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

LMS Salesforce project/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LMS Salesforce project/force-app/main/default/objects/Student__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LMS Salesforce project/force-app/main/default/classes/CertificateService.cls
public with sharing class CertificateService {
    public static void generateCertificate(Id studentId, Id courseId, Id enrollmentId) {
        Enrollment__c enrollment = [SELECT Id, Status__c FROM Enrollment__c WHERE Id = :enrollmentId LIMIT 1];

        Map<String, Id> statusMap = new Map<String,Id>();
        for(Status__c busc : [SELECT Id, Name FROM Status__c WHERE Name IN ('Completed', 'On Hold')]){
            statusMap.put(busc.Name, busc.Id);
        }
            
        
        if(enrollment.Status__c == statusMap.get('On Hold')){
            throw new AuraHandledException('Enrollment is on hold');
        }
        
        Id completedStatusId = [SELECT Id FROM Status__c WHERE Name = 'Completed' LIMIT 1].Id;
        if(enrollment.Status__c == statusMap.get('Completed')){
            throw new AuraHandledException('Enrollment is completed');
        }

        Certificate__c cert = new Certificate__c();
        cert.Enrollment__c = enrollment.Id;
        cert.Student__c = studentId;
        cert.Date__c = Date.today();
        cert.Course__c = courseId;
        cert.Status__c = completedStatusId;
        insert cert;

        enrollment.Status__c = completedStatusId;
        update enrollment;
        

    }
}